port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:
  - {name: 103.93.56.151:57478, server: 103.93.56.151, port: 57478, type: ss, cipher: chacha20-ietf-poly1305, password: ku382YXK8cLE}
  - {name: 104.200.131.165:33992, server: 104.200.131.165, port: 33992, type: ss, cipher: aes-256-gcm, password: 8n6pwAcrrv2pj6tFY2p3TbQ6}
  - {name: 212.102.44.83:35294, server: 212.102.44.83, port: 35294, type: ss, cipher: aes-256-gcm, password: J9Y2ncrdPEC38gwydNFFGBna}
  - {name: 221.228.99.37:8888, server: 221.228.99.37, port: 8888, type: ss, cipher: aes-256-cfb, password: !<str> 123}
  - {name: 84.17.35.118:34815, server: 84.17.35.118, port: 34815, type: ss, cipher: aes-256-gcm, password: LkFAzkzXkSCRYa2CsRdL8cGb}
  - {name: 84.17.35.118:47027, server: 84.17.35.118, port: 47027, type: ss, cipher: aes-256-gcm, password: Vt5pBJFwdtNB26cJbTXxm88Z}
  - {name: CA_53, server: 142.47.219.13, port: 2087, type: vmess, uuid: bce319a6-c1e1-11eb-8936-0050569b2f15, alterId: 0, cipher: auto, tls: true, skip-cert-verify: false, network: ws, ws-path: /OW1k0fXV/, ws-headers: {Host: a4.ssrsub.one}}
  - {name: CA_57, server: 45.62.233.142, port: 2087, type: vmess, uuid: bf53c406-c1e1-11eb-a686-0050569bb8c9, alterId: 0, cipher: auto, tls: true, skip-cert-verify: false, network: ws, ws-path: /hBozMgCA/, ws-headers: {Host: a3.ssrsub.one}}
  - {name: GB ğŸ‡¬ğŸ‡§ London 1, server: 217.146.82.185, port: 31764, type: ss, cipher: aes-256-gcm, password: YgusH2MWA8PWc3p2VDsR7AVv}
  - {name: GB ğŸ‡¬ğŸ‡§ London 1 2, server: 217.146.82.185, port: 50024, type: ss, cipher: aes-256-gcm, password: b2jDPHUQxCNa2KmGHZjy7C4B}
  - {name: GB_1001, server: 185.44.76.188, port: 31572, type: ss, cipher: aes-256-gcm, password: n8w4StnbVD9dmXYn4Ajt87EA}
  - {name: GB_1103, server: 185.44.76.188, port: 31764, type: ss, cipher: aes-256-gcm, password: YgusH2MWA8PWc3p2VDsR7AVv}
  - {name: GB_998, server: 185.38.150.124, port: 31572, type: ss, cipher: aes-256-gcm, password: n8w4StnbVD9dmXYn4Ajt87EA}
  - {name: HR_1164, server: 85.10.50.164, port: 40093, type: ss, cipher: aes-256-gcm, password: x23Z4LGkGDkThZ9Kaz4DURQp}
  - {name: HR_1172, server: 85.10.50.164, port: 39772, type: ss, cipher: aes-256-gcm, password: CUndSZnYsPKcu6Kj8THVMBHD}
  - {name: HR_1176, server: 85.10.50.164, port: 37588, type: ss, cipher: aes-256-gcm, password: kD9vkjnE6dsUzwQfvKkPkQAd}
  - {name: IN_1268, server: 137.59.52.107, port: 39772, type: ss, cipher: aes-256-gcm, password: CUndSZnYsPKcu6Kj8THVMBHD}
  - {name: IN_1272, server: 137.59.52.107, port: 33992, type: ss, cipher: aes-256-gcm, password: 8n6pwAcrrv2pj6tFY2p3TbQ6}
  - {name: IN_1290, server: 137.59.52.107, port: 40093, type: ss, cipher: aes-256-gcm, password: x23Z4LGkGDkThZ9Kaz4DURQp}
  - {name: LT_1464, server: 194.41.112.14, port: 39772, type: ss, cipher: aes-256-gcm, password: CUndSZnYsPKcu6Kj8THVMBHD}
  - {name: ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1, server: 91.90.123.115, port: 31764, type: ss, cipher: aes-256-gcm, password: YgusH2MWA8PWc3p2VDsR7AVv}
  - {name: ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1 2, server: 91.90.123.115, port: 50024, type: ss, cipher: aes-256-gcm, password: b2jDPHUQxCNa2KmGHZjy7C4B}
  - {name: ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1 3, server: 91.90.123.115, port: 31572, type: ss, cipher: aes-256-gcm, password: n8w4StnbVD9dmXYn4Ajt87EA}
  - {name: ğŸ‡¨ğŸ‡³ CN_411, server: 221.228.99.37, port: 8888, type: ss, cipher: aes-256-cfb, password: !<str> 123}
  - {name: ğŸ‡©ğŸ‡ª DE_517, server: 176.227.241.24, port: 33992, type: ss, cipher: aes-256-gcm, password: 8n6pwAcrrv2pj6tFY2p3TbQ6}
  - {name: ğŸ‡«ğŸ‡· FR_818, server: 51.195.62.220, port: 811, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: ğŸ‡«ğŸ‡· FR_953, server: 51.195.62.220, port: 808, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: ğŸ‡¯ğŸ‡µ Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_713, server: 104.19.1.168, port: 443, type: vmess, uuid: f299184b-19e0-41a4-9b4b-65fa8f0e691c, alterId: 64, cipher: auto, tls: true, skip-cert-verify: false, network: ws, ws-path: /jj, ws-headers: {Host: c-jp1.ooxc.cc}}
  - {name: ğŸ‡µğŸ‡­ PH ğŸ‡µğŸ‡­ Manila, server: 45.134.224.15, port: 31572, type: ss, cipher: aes-256-gcm, password: n8w4StnbVD9dmXYn4Ajt87EA}
  - {name: ğŸ‡·ğŸ‡´ RO_1838, server: 91.90.123.155, port: 31572, type: ss, cipher: aes-256-gcm, password: n8w4StnbVD9dmXYn4Ajt87EA}
  - {name: ğŸ‡·ğŸ‡´ RO_1842, server: 193.29.106.197, port: 31572, type: ss, cipher: aes-256-gcm, password: n8w4StnbVD9dmXYn4Ajt87EA}
  - {name: ğŸ‡·ğŸ‡º RU_1918, server: 80.85.156.31, port: 40331, type: vmess, uuid: f3dc16e3-715c-4839-abd3-8e0c6df46064, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false}
  - {name: ğŸ‡·ğŸ‡º RU_1919, server: 45.135.135.93, port: 8080, type: vmess, uuid: 884688eb-d63b-4186-961d-f3b5deac45de, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-path: /, ws-headers: {Host: m.t.17186.cn}}
  - {name: ğŸ‡¸ğŸ‡¬ SG_1953, server: 89.187.163.215, port: 33992, type: ss, cipher: aes-256-gcm, password: 8n6pwAcrrv2pj6tFY2p3TbQ6}
  - {name: ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_4963, server: ac2088.herokuapp.com, port: 443, type: vmess, uuid: d1babe08-f8ac-490b-b66f-9be27467f3cc, alterId: 0, cipher: auto, tls: true, skip-cert-verify: false, network: ws, ws-path: /d1babe08-f8ac-490b-b66f-9be27467f3cc-vmess, ws-headers: {Host: ac2088.herokuapp.com}}
  - {name: ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_718, server: ac2088.herokuapp.com, port: 443, type: vmess, uuid: d1babe08-f8ac-490b-b66f-9be27467f3cc, alterId: 0, cipher: auto, tls: true, skip-cert-verify: false, network: ws, ws-path: /d1babe08-f8ac-490b-b66f-9be27467f3cc-vmess, ws-headers: {Host: ac2088.herokuapp.com}}
  - {name: ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4, server: 138.199.42.133, port: 31764, type: ss, cipher: aes-256-gcm, password: YgusH2MWA8PWc3p2VDsR7AVv}
  - {name: ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 2, server: 138.199.42.133, port: 50024, type: ss, cipher: aes-256-gcm, password: b2jDPHUQxCNa2KmGHZjy7C4B}
  - {name: ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 3, server: 138.199.42.133, port: 31572, type: ss, cipher: aes-256-gcm, password: n8w4StnbVD9dmXYn4Ajt87EA}
  - {name: ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Salt Lake City 2, server: 104.200.131.165, port: 50024, type: ss, cipher: aes-256-gcm, password: b2jDPHUQxCNa2KmGHZjy7C4B}
  - {name: ğŸ‡ºğŸ‡² US_2125, server: 212.102.44.83, port: 40093, type: ss, cipher: aes-256-gcm, password: x23Z4LGkGDkThZ9Kaz4DURQp}
  - {name: ğŸ‡ºğŸ‡² US_2192, server: 84.17.35.118, port: 49126, type: ss, cipher: aes-256-gcm, password: wrCaGtrUbzeRqQLdc8Kmk3Nd}
  - {name: ğŸ‡ºğŸ‡² US_2214, server: 148.72.169.213, port: 33992, type: ss, cipher: aes-256-gcm, password: 8n6pwAcrrv2pj6tFY2p3TbQ6}
  - {name: ğŸ‡ºğŸ‡² US_2276, server: 66.55.148.42, port: 810, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: ğŸ‡ºğŸ‡² US_2392, server: 143.244.60.164, port: 39772, type: ss, cipher: aes-256-gcm, password: CUndSZnYsPKcu6Kj8THVMBHD}
  - {name: ğŸ‡ºğŸ‡² US_2422, server: 207.244.67.149, port: 33998, type: ss, cipher: aes-256-gcm, password: NHwQTPLCfaTMSqTnU3mjcSxe}
  - {name: ğŸ‡ºğŸ‡² US_2460, server: 23.82.11.49, port: 39772, type: ss, cipher: aes-256-gcm, password: CUndSZnYsPKcu6Kj8THVMBHD}
  - {name: ğŸ‡ºğŸ‡² US_2472, server: 84.17.35.118, port: 49396, type: ss, cipher: aes-256-gcm, password: BdRWC38L5JUDMTYNNxJGcUwB}
  - {name: ğŸ‡ºğŸ‡² US_2543, server: 143.244.42.71, port: 31572, type: ss, cipher: aes-256-gcm, password: n8w4StnbVD9dmXYn4Ajt87EA}
  - {name: ğŸ‡ºğŸ‡² US_2556, server: 23.82.11.49, port: 37588, type: ss, cipher: aes-256-gcm, password: kD9vkjnE6dsUzwQfvKkPkQAd}
  - {name: ğŸ‡ºğŸ‡² US_2567, server: 84.17.35.78, port: 33992, type: ss, cipher: aes-256-gcm, password: 8n6pwAcrrv2pj6tFY2p3TbQ6}
  - {name: ğŸ‡ºğŸ‡² US_2576, server: 84.17.35.118, port: 48938, type: ss, cipher: aes-256-gcm, password: 4ejJ8n5ddLuYDUHGXJre2ufJ}
proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ”¯ æ•…éšœè½¬ç§»
      - ğŸ”® è´Ÿè½½å‡è¡¡
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    proxies:
      - 103.93.56.151:57478
      - 104.200.131.165:33992
      - 212.102.44.83:35294
      - 221.228.99.37:8888
      - 84.17.35.118:34815
      - 84.17.35.118:47027
      - CA_53
      - CA_57
      - GB ğŸ‡¬ğŸ‡§ London 1
      - GB ğŸ‡¬ğŸ‡§ London 1 2
      - GB_1001
      - GB_1103
      - GB_998
      - HR_1164
      - HR_1172
      - HR_1176
      - IN_1268
      - IN_1272
      - IN_1290
      - LT_1464
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1 2
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1 3
      - ğŸ‡¨ğŸ‡³ CN_411
      - ğŸ‡©ğŸ‡ª DE_517
      - ğŸ‡«ğŸ‡· FR_818
      - ğŸ‡«ğŸ‡· FR_953
      - ğŸ‡¯ğŸ‡µ Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_713
      - ğŸ‡µğŸ‡­ PH ğŸ‡µğŸ‡­ Manila
      - ğŸ‡·ğŸ‡´ RO_1838
      - ğŸ‡·ğŸ‡´ RO_1842
      - ğŸ‡·ğŸ‡º RU_1918
      - ğŸ‡·ğŸ‡º RU_1919
      - ğŸ‡¸ğŸ‡¬ SG_1953
      - ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_4963
      - ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_718
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 2
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 3
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Salt Lake City 2
      - ğŸ‡ºğŸ‡² US_2125
      - ğŸ‡ºğŸ‡² US_2192
      - ğŸ‡ºğŸ‡² US_2214
      - ğŸ‡ºğŸ‡² US_2276
      - ğŸ‡ºğŸ‡² US_2392
      - ğŸ‡ºğŸ‡² US_2422
      - ğŸ‡ºğŸ‡² US_2460
      - ğŸ‡ºğŸ‡² US_2472
      - ğŸ‡ºğŸ‡² US_2543
      - ğŸ‡ºğŸ‡² US_2556
      - ğŸ‡ºğŸ‡² US_2567
      - ğŸ‡ºğŸ‡² US_2576
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 103.93.56.151:57478
      - 104.200.131.165:33992
      - 212.102.44.83:35294
      - 221.228.99.37:8888
      - 84.17.35.118:34815
      - 84.17.35.118:47027
      - CA_53
      - CA_57
      - GB ğŸ‡¬ğŸ‡§ London 1
      - GB ğŸ‡¬ğŸ‡§ London 1 2
      - GB_1001
      - GB_1103
      - GB_998
      - HR_1164
      - HR_1172
      - HR_1176
      - IN_1268
      - IN_1272
      - IN_1290
      - LT_1464
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1 2
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1 3
      - ğŸ‡¨ğŸ‡³ CN_411
      - ğŸ‡©ğŸ‡ª DE_517
      - ğŸ‡«ğŸ‡· FR_818
      - ğŸ‡«ğŸ‡· FR_953
      - ğŸ‡¯ğŸ‡µ Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_713
      - ğŸ‡µğŸ‡­ PH ğŸ‡µğŸ‡­ Manila
      - ğŸ‡·ğŸ‡´ RO_1838
      - ğŸ‡·ğŸ‡´ RO_1842
      - ğŸ‡·ğŸ‡º RU_1918
      - ğŸ‡·ğŸ‡º RU_1919
      - ğŸ‡¸ğŸ‡¬ SG_1953
      - ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_4963
      - ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_718
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 2
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 3
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Salt Lake City 2
      - ğŸ‡ºğŸ‡² US_2125
      - ğŸ‡ºğŸ‡² US_2192
      - ğŸ‡ºğŸ‡² US_2214
      - ğŸ‡ºğŸ‡² US_2276
      - ğŸ‡ºğŸ‡² US_2392
      - ğŸ‡ºğŸ‡² US_2422
      - ğŸ‡ºğŸ‡² US_2460
      - ğŸ‡ºğŸ‡² US_2472
      - ğŸ‡ºğŸ‡² US_2543
      - ğŸ‡ºğŸ‡² US_2556
      - ğŸ‡ºğŸ‡² US_2567
      - ğŸ‡ºğŸ‡² US_2576
  - name: ğŸ”¯ æ•…éšœè½¬ç§»
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 103.93.56.151:57478
      - 104.200.131.165:33992
      - 212.102.44.83:35294
      - 221.228.99.37:8888
      - 84.17.35.118:34815
      - 84.17.35.118:47027
      - CA_53
      - CA_57
      - GB ğŸ‡¬ğŸ‡§ London 1
      - GB ğŸ‡¬ğŸ‡§ London 1 2
      - GB_1001
      - GB_1103
      - GB_998
      - HR_1164
      - HR_1172
      - HR_1176
      - IN_1268
      - IN_1272
      - IN_1290
      - LT_1464
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1 2
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1 3
      - ğŸ‡¨ğŸ‡³ CN_411
      - ğŸ‡©ğŸ‡ª DE_517
      - ğŸ‡«ğŸ‡· FR_818
      - ğŸ‡«ğŸ‡· FR_953
      - ğŸ‡¯ğŸ‡µ Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_713
      - ğŸ‡µğŸ‡­ PH ğŸ‡µğŸ‡­ Manila
      - ğŸ‡·ğŸ‡´ RO_1838
      - ğŸ‡·ğŸ‡´ RO_1842
      - ğŸ‡·ğŸ‡º RU_1918
      - ğŸ‡·ğŸ‡º RU_1919
      - ğŸ‡¸ğŸ‡¬ SG_1953
      - ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_4963
      - ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_718
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 2
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 3
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Salt Lake City 2
      - ğŸ‡ºğŸ‡² US_2125
      - ğŸ‡ºğŸ‡² US_2192
      - ğŸ‡ºğŸ‡² US_2214
      - ğŸ‡ºğŸ‡² US_2276
      - ğŸ‡ºğŸ‡² US_2392
      - ğŸ‡ºğŸ‡² US_2422
      - ğŸ‡ºğŸ‡² US_2460
      - ğŸ‡ºğŸ‡² US_2472
      - ğŸ‡ºğŸ‡² US_2543
      - ğŸ‡ºğŸ‡² US_2556
      - ğŸ‡ºğŸ‡² US_2567
      - ğŸ‡ºğŸ‡² US_2576
  - name: ğŸ”® è´Ÿè½½å‡è¡¡
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 103.93.56.151:57478
      - 104.200.131.165:33992
      - 212.102.44.83:35294
      - 221.228.99.37:8888
      - 84.17.35.118:34815
      - 84.17.35.118:47027
      - CA_53
      - CA_57
      - GB ğŸ‡¬ğŸ‡§ London 1
      - GB ğŸ‡¬ğŸ‡§ London 1 2
      - GB_1001
      - GB_1103
      - GB_998
      - HR_1164
      - HR_1172
      - HR_1176
      - IN_1268
      - IN_1272
      - IN_1290
      - LT_1464
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1 2
      - ğŸ‡§ğŸ‡ª BE ğŸ‡§ğŸ‡ª Brussels 1 3
      - ğŸ‡¨ğŸ‡³ CN_411
      - ğŸ‡©ğŸ‡ª DE_517
      - ğŸ‡«ğŸ‡· FR_818
      - ğŸ‡«ğŸ‡· FR_953
      - ğŸ‡¯ğŸ‡µ Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_713
      - ğŸ‡µğŸ‡­ PH ğŸ‡µğŸ‡­ Manila
      - ğŸ‡·ğŸ‡´ RO_1838
      - ğŸ‡·ğŸ‡´ RO_1842
      - ğŸ‡·ğŸ‡º RU_1918
      - ğŸ‡·ğŸ‡º RU_1919
      - ğŸ‡¸ğŸ‡¬ SG_1953
      - ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_4963
      - ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_718
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 2
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 3
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Salt Lake City 2
      - ğŸ‡ºğŸ‡² US_2125
      - ğŸ‡ºğŸ‡² US_2192
      - ğŸ‡ºğŸ‡² US_2214
      - ğŸ‡ºğŸ‡² US_2276
      - ğŸ‡ºğŸ‡² US_2392
      - ğŸ‡ºğŸ‡² US_2422
      - ğŸ‡ºğŸ‡² US_2460
      - ğŸ‡ºğŸ‡² US_2472
      - ğŸ‡ºğŸ‡² US_2543
      - ğŸ‡ºğŸ‡² US_2556
      - ğŸ‡ºğŸ‡² US_2567
      - ğŸ‡ºğŸ‡² US_2576
  - name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ“¹ æ²¹ç®¡è§†é¢‘
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ¥ å¥ˆé£è§†é¢‘
    type: select
    proxies:
      - ğŸ¥ å¥ˆé£èŠ‚ç‚¹
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ“º å·´å“ˆå§†ç‰¹
    type: select
    proxies:
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸŒ å›½å†…åª’ä½“
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸŒ å‡ºæµ·åª’ä½“
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ“¢ è°·æ­ŒFCM
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: â“‚ï¸ å¾®è½¯äº‘ç›˜
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ® æ¸¸æˆå¹³å°
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ¶ ç½‘æ˜“éŸ³ä¹
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸƒ åº”ç”¨å‡€åŒ–
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸ† AdBlock
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸ›¡ï¸ éšç§é˜²æŠ¤
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - DIRECT
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡¯ğŸ‡µ Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_713
  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡¯ğŸ‡µ Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_713
      - ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_4963
      - ğŸ‡ºğŸ‡² Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_718
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 2
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Chicago 4 3
      - ğŸ‡ºğŸ‡² US ğŸ‡ºğŸ‡¸ Salt Lake City 2
      - ğŸ‡ºğŸ‡² US_2125
      - ğŸ‡ºğŸ‡² US_2192
      - ğŸ‡ºğŸ‡² US_2214
      - ğŸ‡ºğŸ‡² US_2276
      - ğŸ‡ºğŸ‡² US_2392
      - ğŸ‡ºğŸ‡² US_2422
      - ğŸ‡ºğŸ‡² US_2460
      - ğŸ‡ºğŸ‡² US_2472
      - ğŸ‡ºğŸ‡² US_2543
      - ğŸ‡ºğŸ‡² US_2556
      - ğŸ‡ºğŸ‡² US_2567
      - ğŸ‡ºğŸ‡² US_2576
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - DIRECT
  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡¸ğŸ‡¬ SG_1953
  - name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - DIRECT
  - name: ğŸ¥ å¥ˆé£èŠ‚ç‚¹
    type: select
    proxies:
      - DIRECT
rules:
 - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
 - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

